### ISSUE TITLE
When should we use preload?

### ISSUE THREAD

**Issue by 149203** [rishi-raj-jain/astro-font#18]
I noticed on your own sites (for example, line 40 here: https://github.com/rishi-raj-jain/suplovers-astro/blob/main/src/layouts/Layout.astro) you are setting `preload: false` when serving a local font.

When should we use `preload: true` and `preload: false`? Can you give some examples?

Thank you!

**Comment by rishi-raj-jain** [comment]
Hey @149203,

Great question.

Just wanted to clear that the website is an Astro port of https://github.com/AlejandroMar/suplovers and not my own. I must have forked it to showcase the usage, because I've done ~100 PRs highlighting integration of `astro-font` in all possible scenarios.

But anyways, I appreciate your question, and here's the answer:

- Using preload is not affected with the origin of font, whether local or over CDN.
- Using preload is specific to the nature of your website font loads and their priority:
   - Case 1: If I have say a designer website with fonts of very specific kind and I'm okay with users seeing a fallback font (generated to match the font of your choice) I do not need to use preload. Having a fallback font allows me to get rid of layout shifts.
   - Case 2: If I have say a designer website with fonts of very specific kind BUT I'm NOT okay with users seeing a fallback font, I do need to use preload to make sure that the fonts receive higher priority on the network waterfall.
   - Case 3: If I do not have a designer website but still I want the font of my choice to be visible to users as soon as they open up the page, I'd need to use preload.
   - Case 4: If I do not have a designer website and I'm okay with users seeing a fallback font I do not need to use preload. Having a fallback font allows me to get rid of layout shifts.

Hope this makes sense.

**Comment by 149203** [comment]
@rishi-raj-jain thank you!

Can we specify multiple fallback fonts with astro-font? How? The examples show a single string.

Thanks again!

**Comment by rishi-raj-jain** [comment]
@149203 

What do you mean by multiple fallbacks? Any specific you've in mind?

**Comment by 149203** [comment]
In my Tailwind config, I can do the following:

```
fontFamily: {
      heading: ["var(--font-spline-sans)", ...defaultTheme.fontFamily.sans],
    },
```

where `...defaultTheme.fontFamily.sans` extracts all the fallbacks from the default sans-serifs set by Tailwind. These are:

```
ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
```

as described here: https://tailwindcss.com/docs/font-family

So it will look for the custom font, then the next best sans-serif fonts.

**Comment by rishi-raj-jain** [comment]
Oh I see, what would you propose?

**Comment by 149203** [comment]
Perhaps `fallback` being able to handle an array or string?

Frankly, it's not a critical issue. I was just wondering if astro-font had support for it. It could make fallback fonts look nicer when `preload` is false.

**Comment by rishi-raj-jain** [comment]
> Perhaps fallback being able to handle an array or string?

How may I generate the fallbacks for each of them? Currently, `serif`, `sans-serif` and `monospace` are supported.

**Comment by rishi-raj-jain** [comment]
Oh I think yes, I can do both:

- allow people to mention fallback but improve the utils to not set the `serif/sans-serif/monospace` by itself.
- allow people to add `restFallbackFonts` that'll just be just passed on.

**Comment by rishi-raj-jain** [comment]
https://www.launchfa.st/blog/when-to-preload-fonts
